import { useState, useEffect, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useTheme } from '../contexts/ThemeContext';
import DisclaimerBanner from '../components/DisclaimerBanner';
import HealthSpectrum from '../components/HealthSpectrum';
import OrganSystemCard from '../components/OrganSystemCard';
import ParameterDetail from '../components/ParameterDetail';
import ReadAloud from '../components/ReadAloud';
import { saveReport } from '../utils/storage';

const STATUS_FILTERS = ['all', 'excellent', 'normal', 'needs_attention', 'review_recommended'];
const STATUS_ICONS = { all: '', excellent: '🟢', normal: '🔵', needs_attention: '🟡', review_recommended: '🔴' };

export default function DashboardPage() {
  const { t } = useTranslation();
  const { simpleMode } = useTheme();
  const navigate = useNavigate();
  const [analysis, setAnalysis] = useState(null);
  const [filter, setFilter] = useState('all');
  const [expandedSystem, setExpandedSystem] = useState(null);
  const [view, setView] = useState('organs');
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);
  const [truncatedPages, setTruncatedPages] = useState(null);

  useEffect(() => {
    const data = sessionStorage.getItem('ld-analysis-result');
    if (data) {
      try { setAnalysis(JSON.parse(data)); }
      catch { navigate('/upload', { replace: true }); }
    } else {
      navigate('/upload', { replace: true });
    }
    // Check for truncated pages
    const truncated = sessionStorage.getItem('ld-truncated-pages');
    if (truncated) setTruncatedPages(parseInt(truncated, 10));
  }, []);

  const handleSave = () => {
    if (analysis && !saved) {
      saveReport({
        name: analysis.lab_name ? `${analysis.lab_name} Report` : `Report ${analysis.report_date || new Date().toLocaleDateString()}`,
        date: analysis.report_date || new Date().toISOString(),
        labName: analysis.lab_name,
        patientName: analysis.patient_name,
        analysis,
      });
      setSaved(true);
    }
  };

  // Group by organ system
  const systems = useMemo(() => {
    if (!analysis?.parameters) return {};
    const grouped = {};
    analysis.parameters.forEach(p => {
      const sys = p.organ_system || 'other';
      if (!grouped[sys]) grouped[sys] = [];
      grouped[sys].push(p);
    });
    return grouped;
  }, [analysis]);

  // Filter parameters
  const filteredParams = useMemo(() => {
    if (!analysis?.parameters) return [];
    if (filter === 'all') return analysis.parameters;
    return analysis.parameters.filter(p => p.status === filter);
  }, [analysis, filter]);

  const counts = useMemo(() => {
    if (!analysis?.parameters) return { excellent: 0, normal: 0, attention: 0, review: 0, inRange: 0, outRange: 0 };
    const excellent = analysis.parameters.filter(p => p.status === 'excellent').length;
    const normal = analysis.parameters.filter(p => p.status === 'normal').length;
    const attention = analysis.parameters.filter(p => p.status === 'needs_attention').length;
    const review = analysis.parameters.filter(p => p.status === 'review_recommended').length;
    return { excellent, normal, attention, review, inRange: excellent + normal, outRange: attention + review };
  }, [analysis]);

  // Copy summary to clipboard
  const handleCopySummary = useCallback(() => {
    if (!analysis) return;
    const total = analysis.total_parameters || analysis.parameters?.length || 0;
    const date = analysis.report_date || new Date().toLocaleDateString();
    const attentionParams = analysis.parameters
      ?.filter(p => p.status === 'needs_attention' || p.status === 'review_recommended')
      .map(p => `${p.name} (${p.status === 'review_recommended' ? 'review' : 'attention'})`)
      .join(', ');

    const text = `My LabDecode Report (${date}): ${total} parameters analyzed. ${counts.inRange} normal, ${counts.outRange} need attention.${attentionParams ? ` Key items: ${attentionParams}.` : ''}\n\nGenerated by LabDecode — https://read-my-report.vercel.app`;

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  }, [analysis, counts]);

  // Email to doctor
  const handleEmailDoctor = useCallback(() => {
    if (!analysis) return;
    const total = analysis.total_parameters || analysis.parameters?.length || 0;
    const subject = encodeURIComponent(`Lab Report Analysis — ${analysis.report_date || new Date().toLocaleDateString()}`);
    const attentionParams = analysis.parameters
      ?.filter(p => p.status === 'needs_attention' || p.status === 'review_recommended')
      .map(p => `- ${p.name}: ${p.value} ${p.unit} (${p.status === 'review_recommended' ? 'Review Recommended' : 'Needs Attention'})`)
      .join('\n');
    const body = encodeURIComponent(
      `Dear Doctor,\n\nI recently had lab work done and used LabDecode to understand my results. Here is a summary:\n\n` +
      `Total parameters: ${total}\nIn range: ${counts.inRange}\nNeed attention: ${counts.outRange}\n\n` +
      (attentionParams ? `Parameters that may need review:\n${attentionParams}\n\n` : '') +
      `I would appreciate your guidance on these results.\n\nNote: This summary was generated by LabDecode, an educational tool. It is not a medical diagnosis.`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`);
  }, [analysis, counts]);

  if (!analysis) return null;

  const summaryText = `${analysis.summary || ''} ${analysis.total_parameters || analysis.parameters?.length || 0} parameters were tested. ${counts.inRange} are in range and ${counts.outRange} need attention.`;

  return (
    <div style={{ maxWidth: '1000px', margin: '0 auto', padding: '1.5rem' }}>
      {/* Disclaimer Banner */}
      <DisclaimerBanner style={{ marginBottom: '1.5rem' }} />

      {/* Truncation Warning */}
      {truncatedPages && (
        <div className="animate-fade-in" style={{
          background: 'linear-gradient(135deg, #FFFBEB, #FEF3C7)',
          border: '1px solid #F59E0B',
          borderRadius: 'var(--radius-sm)',
          padding: '0.75rem 1rem',
          marginBottom: '1rem',
          fontSize: '0.85rem',
          color: '#92400E',
          lineHeight: 1.5,
        }}>
          Your report had {truncatedPages} pages. We analyzed the first 6 for best accuracy. Some parameters from later pages may not appear.
        </div>
      )}

      {/* Summary Card with gradient */}
      <div className="card animate-slide-up" style={{
        marginBottom: '1.5rem',
        background: 'linear-gradient(135deg, rgba(15,118,110,0.04), rgba(14,165,233,0.04))',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ flex: 1, minWidth: '250px' }}>
            <h1 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.5rem' }}>{t('dashboard.summary')}</h1>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: '0.95rem', marginBottom: '1rem' }}>
              {analysis.summary}
            </p>
            {/* Stats row */}
            <div style={{ display: 'flex', gap: '1.5rem', flexWrap: 'wrap', marginBottom: '1rem' }}>
              <div>
                <span style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0F766E' }}>{analysis.total_parameters || analysis.parameters?.length}</span>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginLeft: '0.375rem' }}>{t('dashboard.parameters_tested')}</span>
              </div>
              <div>
                <span style={{ fontSize: '1.5rem', fontWeight: 700, color: '#10B981' }}>{counts.inRange}</span>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginLeft: '0.375rem' }}>{t('dashboard.in_range')}</span>
              </div>
              <div>
                <span style={{ fontSize: '1.5rem', fontWeight: 700, color: '#F59E0B' }}>{counts.outRange}</span>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginLeft: '0.375rem' }}>{t('dashboard.out_of_range')}</span>
              </div>
            </div>
            {analysis.report_date && (
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                📅 {t('dashboard.report_date')}: {analysis.report_date}
                {analysis.lab_name && <> · 🏥 {analysis.lab_name}</>}
              </p>
            )}
            {(analysis.patient_name || analysis.patient_age || analysis.patient_sex) && (
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
                👤 {analysis.patient_name ? `${analysis.patient_name}` : 'Patient'}: {analysis.patient_age ? `${analysis.patient_age} ` : ''}{analysis.patient_sex || ''}
              </p>
            )}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', alignItems: 'flex-end' }}>
            <ReadAloud text={summaryText} />
            <button className="btn btn-secondary" onClick={handleSave} style={{ fontSize: '0.85rem' }}>
              {saved ? '✓ Saved' : '💾 Save Report'}
            </button>
            <button className="btn btn-ghost" onClick={handleCopySummary} style={{ fontSize: '0.85rem' }}>
              {copied ? '✓ Copied!' : '📋 Copy Summary'}
            </button>
            <button className="btn btn-ghost" onClick={handleEmailDoctor} style={{ fontSize: '0.85rem' }}>
              ✉️ Email to Doctor
            </button>
          </div>
        </div>
        <HealthSpectrum parameters={analysis.parameters} />
      </div>

      {/* View Toggle & Filters */}
      <div className="animate-slide-up" style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        marginBottom: '1rem', flexWrap: 'wrap', gap: '0.75rem',
      }}>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button
            className={`btn ${view === 'organs' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setView('organs')}
            style={{ padding: '0.5rem 1rem', fontSize: '0.85rem' }}
          >
            🫀 {t('dashboard.organ_systems')}
          </button>
          <button
            className={`btn ${view === 'list' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setView('list')}
            style={{ padding: '0.5rem 1rem', fontSize: '0.85rem' }}
          >
            📋 {t('dashboard.all_parameters')}
          </button>
        </div>
        <button className="btn btn-ghost" onClick={() => navigate('/lifestyle')} style={{ fontSize: '0.85rem' }}>
          🌿 {t('dashboard.lifestyle')}
        </button>
      </div>

      {/* Status Filters */}
      <div style={{
        display: 'flex', gap: '0.375rem', marginBottom: '1.5rem',
        overflowX: 'auto', paddingBottom: '0.25rem',
        WebkitOverflowScrolling: 'touch',
      }}>
        {STATUS_FILTERS.map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`btn ${filter === f ? 'btn-primary' : 'btn-ghost'}`}
            style={{ padding: '0.375rem 0.75rem', fontSize: '0.8rem', borderRadius: '999px', whiteSpace: 'nowrap' }}
          >
            {STATUS_ICONS[f] ? `${STATUS_ICONS[f]} ` : ''}
            {f === 'all' ? t('dashboard.filter_all') : t(`dashboard.filter_${f === 'needs_attention' ? 'attention' : f === 'review_recommended' ? 'review' : f}`)}
          </button>
        ))}
      </div>

      {view === 'organs' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginBottom: '1.5rem' }}>
          {Object.entries(systems).map(([sys, params]) => {
            const filteredSystemParams = filter === 'all' ? params : params.filter(p => p.status === filter);
            if (filteredSystemParams.length === 0) return null;
            return (
              <div key={sys}>
                <OrganSystemCard
                  system={sys}
                  parameters={filteredSystemParams}
                  expanded={expandedSystem === sys}
                  onClick={() => setExpandedSystem(expandedSystem === sys ? null : sys)}
                />
                {expandedSystem === sys && (
                  <div style={{ marginTop: '0.5rem' }}>
                    {filteredSystemParams.map((p, i) => (
                      <ParameterDetail key={i} parameter={p} simple={simpleMode} />
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* List View */}
      {view === 'list' && (
        <div>
          {filteredParams.map((p, i) => (
            <ParameterDetail key={i} parameter={p} simple={simpleMode} />
          ))}
          {filteredParams.length === 0 && (
            <p style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>
              No parameters match this filter.
            </p>
          )}
        </div>
      )}

      {/* Bottom spacer for mobile nav */}
      <div className="mobile-bottom-spacer" />
    </div>
  );
}
